package org.leetcode.hard;


/**
 * <b>#3474 - Lexicographically Smallest Generated String</b>
 *
 * <p><b>Difficulty:</b> Hard</p>
 * <p><b>Category:</b> String, Greedy, String Matching</p>
 *
 * <h2>Problem Description</h2>
 * <pre>
 * You are given two strings, str1 and str2, of lengths n and m, respectively.
 *
 *
 * A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 &lt;= i &lt;= n - 1:
 *
 *
 * If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
 *
 * If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
 *
 * Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".
 *
 *
 *
 *
 * Example 1:
 *
 * Input: str1 = "TFTF", str2 = "ab"
 *
 *
 * Output: "ababa"
 *
 *
 * Explanation:
 *
 * The table below represents the string "ababa"
 *
 *
 *
 *
 *
 * 			Index
 * 			T/F
 * 			Substring of length m
 *
 *
 *
 *
 * 			0
 * 			'T'
 * 			"ab"
 *
 *
 *
 *
 * 			1
 * 			'F'
 * 			"ba"
 *
 *
 *
 *
 * 			2
 * 			'T'
 * 			"ab"
 *
 *
 *
 *
 * 			3
 * 			'F'
 * 			"ba"
 *
 *
 *
 *
 * The strings "ababa" and "ababb" can be generated by str1 and str2.
 *
 *
 * Return "ababa" since it is the lexicographically smaller string.
 *
 * Example 2:
 *
 * Input: str1 = "TFTF", str2 = "abc"
 *
 *
 * Output: ""
 *
 *
 * Explanation:
 *
 *
 * No string that satisfies the conditions can be generated.
 *
 * Example 3:
 *
 * Input: str1 = "F", str2 = "d"
 *
 *
 * Output: "a"
 *
 *
 *
 * Constraints:
 *
 *
 * 1 &lt;= n == str1.length &lt;= 104
 *
 * 1 &lt;= m == str2.length &lt;= 500
 *
 * str1 consists only of 'T' or 'F'.
 *
 * str2 consists only of lowercase English characters.
 * </pre>
 *
 * <h2>Hints to Solve</h2>
 * Hint 1: Use dynamic programming.
 * Hint 2: Fill the fixed part.
 * Hint 3: Use KMP's next table for DP.
 * Hint 4: The state is the prefix length and the longest suffix length that matches the pattern.
 * Hint 5: Each unknown character can be selected from <code>['a', 'b']</code>.
 * Hint 6: Can you think of a greedy approach?
 *
 * <h2>Approach</h2>
 * Think about the category (String, Greedy, String Matching).
 *
 * @see <a href="https://leetcode.com/problems/lexicographically-smallest-generated-string/">LeetCode #3474</a>
 */
public class LexicographicallySmallestGeneratedString {

    /**
     * Solves the problem and Solve.
     *
     * @param input the input (Object)
     * @return the computed Object result
     */
    public Object solve(Object input) {
        throw new UnsupportedOperationException("Not yet implemented: Lexicographically Smallest Generated String");
    }

    public static void main(String[] args) {
        System.out.println("=== LexicographicallySmallestGeneratedString ===");
        LexicographicallySmallestGeneratedString sol = new LexicographicallySmallestGeneratedString();
        System.out.println(sol.solve(null));
    }
}
