package org.leetcode.easy;

/**
 * <b>#389 - Find the Difference</b>
 *
 * <p><b>Difficulty:</b> Easy</p>
 * <p><b>Category:</b> Hash Table, String, Bit Manipulation, Sorting</p>
 *
 * <h2>Problem Description</h2>
 * <pre>
 * You are given two strings s and t.
 * 
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * 
 * Return the letter that was added to t.
 * 
 * 
 *  
 * 
 * Example 1:
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * Example 2:
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 *  
 * 
 * Constraints:
 * 
 * 	
 * 0 &lt;= s.length &lt;= 1000
 * 	
 * t.length == s.length + 1
 * 	
 * s and t consist of lowercase English letters.
 * </pre>
 *
 * <h2>Hints to Solve</h2>
 * No hints — study the examples carefully.
 *
 * <h2>Approach</h2>
 * XOR all characters in both strings; added character is the survivor.
 *
 * <h2>Complexity</h2>
* Time: O(n)  |  Space: O(1)
 *
 * @see <a href="https://leetcode.com/problems/find-the-difference/">LeetCode #389</a>
  *
  * <p><b>Explanation:</b> Searches through the input, returning the first element or index satisfying the target condition.</p>
  */
public class FindTheDifference {

    /**
     * Finds Find the difference.
     *
     * @param s the s (String)
     * @param t the t (String)
     * @return the computed char result
      *
      * <p><b>Explanation:</b> Searches through the input, returning the first element or index satisfying the target condition.</p>
      */
    public char findTheDifference(String s, String t) {
        char x=0;
        for(char c:s.toCharArray()) x^=c;
        for(char c:t.toCharArray()) x^=c;
        return x;
    }

    // ─── Demo ────────────────────────────────────────────────────
    public static void main(String[] args) {
        FindTheDifference sol = new FindTheDifference();
        System.out.println(sol.findTheDifference("abcd","abcde")); // 'e'
        System.out.println(sol.findTheDifference("","a"));          // 'a'
    }
}
