package org.leetcode.easy;


/**
 * <b>#3270 - Find the Key of the Numbers</b>
 *
 * <p><b>Difficulty:</b> Easy</p>
 * <p><b>Category:</b> Math</p>
 *
 * <h2>Problem Description</h2>
 * <pre>
 * You are given three positive integers num1, num2, and num3.
 *
 *
 * The key of num1, num2, and num3 is defined as a four-digit number such that:
 *
 *
 * Initially, if any number has less than four digits, it is padded with leading zeros.
 *
 * The ith digit (1 &lt;= i &lt;= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
 *
 * Return the key of the three numbers without leading zeros (if any).
 *
 *
 *
 *
 * Example 1:
 *
 * Input: num1 = 1, num2 = 10, num3 = 1000
 *
 *
 * Output: 0
 *
 *
 * Explanation:
 *
 *
 * On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".
 *
 *
 * The 1st digit of the key is min(0, 0, 1).
 *
 * The 2nd digit of the key is min(0, 0, 0).
 *
 * The 3rd digit of the key is min(0, 1, 0).
 *
 * The 4th digit of the key is min(1, 0, 0).
 *
 * Hence, the key is "0000", i.e. 0.
 *
 * Example 2:
 *
 * Input: num1 = 987, num2 = 879, num3 = 798
 *
 *
 * Output: 777
 *
 * Example 3:
 *
 * Input: num1 = 1, num2 = 2, num3 = 3
 *
 *
 * Output: 1
 *
 *
 *
 * Constraints:
 *
 *
 * 1 &lt;= num1, num2, num3 &lt;= 9999
 * </pre>
 *
 * <h2>Hints to Solve</h2>
 * No hints -- trace through examples manually.
 *
 * <h2>Approach</h2>
 * Think about the category (Math).
 *
 * @see <a href="https://leetcode.com/problems/find-the-key-of-the-numbers/">LeetCode #3270</a>
  *
  * <p><b>Explanation:</b> Searches through the input, returning the first element or index satisfying the target condition.</p>
  */
public class FindTheKeyOfTheNumbers {

    /**
     * Finds Find kth character.
     *
     * @param k the k (long)
     * @param operations the operations (int[])
     * @return the computed int result
      *
      * <p><b>Explanation:</b> Searches through the input, returning the first element or index satisfying the target condition.</p>
      */
    public int findKthCharacter(long k, int[] operations) {
        // Each operation appends transformed copy; character at position k
        int n=operations.length;
        long len=1L<<n;
        for (int i=n-1;i>=0;i--) {
            long half=1L<<i;
            if (k>half) { k-=half; if (operations[i]==1) return (int)(k-1)%26; }
        }
        return 0; // first char is always 'a'
    }

    public static void main(String[] args) {
        FindTheKeyOfTheNumbers sol = new FindTheKeyOfTheNumbers();
        System.out.println(sol.findKthCharacter(0L, new int[]{1,2,3}));
    }
}
