package org.leetcode.easy;


/**
 * <b>#1332 - Remove Palindromic Subsequences</b>
 *
 * <p><b>Difficulty:</b> Easy</p>
 * <p><b>Category:</b> Two Pointers, String</p>
 *
 * <h2>Problem Description</h2>
 * <pre>
 * You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
 *
 *
 * Return the minimum number of steps to make the given string empty.
 *
 *
 * A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.
 *
 *
 * A string is called palindrome if is one that reads the same backward as well as forward.
 *
 *
 *
 *
 * Example 1:
 *
 * Input: s = "ababa"
 * Output: 1
 * Explanation: s is already a palindrome, so its entirety can be removed in a single step.
 *
 * Example 2:
 *
 * Input: s = "abb"
 * Output: 2
 * Explanation: "abb" -&gt; "bb" -&gt; "". 
 * Remove palindromic subsequence "a" then "bb".
 *
 * Example 3:
 *
 * Input: s = "baabb"
 * Output: 2
 * Explanation: "baabb" -&gt; "b" -&gt; "". 
 * Remove palindromic subsequence "baab" then "b".
 *
 *
 *
 * Constraints:
 *
 *
 * 1 &lt;= s.length &lt;= 1000
 *
 * s[i] is either 'a' or 'b'.
 * </pre>
 *
 * <h2>Hints to Solve</h2>
 * Hint 1: Use the fact that string contains only 2 characters.
 * Hint 2: Are subsequences composed of only one type of letter always palindrome strings ?
 *
 * <h2>Approach</h2>
 * Think about the category (Two Pointers, String).
 * Start brute-force, then optimise: sorting, hashing, two pointers,
 * sliding window, binary search, backtracking, DP, or graph traversal.
 *
 * <h2>Complexity</h2>
 * Time: see implementation  |  Space: see implementation
 *
 * @see <a href="https://leetcode.com/problems/remove-palindromic-subsequences/">LeetCode #1332</a>
  *
  * <p><b>Explanation:</b> Uses StringBuilder for O(1) amortized character appends, avoiding O(n^2) String concatenation.</p>
  */
public class RemovePalindromicSubsequences {

    /**
     * Removes Remove palindrome sub.
     *
     * @param s the s (String)
     * @return the computed int result
      *
      * <p><b>Explanation:</b> Uses StringBuilder for O(1) amortized character appends, avoiding O(n^2) String concatenation.</p>
      */
    public int removePalindromeSub(String s) {
        if (s.isEmpty()) return 0;
        String rev = new StringBuilder(s).reverse().toString();
        return s.equals(rev) ? 1 : 2;
    }

    /**
     * Runs sample test cases.
      *
      * <p><b>Explanation:</b> Processes the string character by character, applying the transformation or predicate.</p>
      */
    public static void main(String[] args) {
        RemovePalindromicSubsequences sol = new RemovePalindromicSubsequences();
                System.out.println(sol.removePalindromeSub("ababa")); // 1 (already palindrome)
                System.out.println(sol.removePalindromeSub("abb"));   // 2
                System.out.println(sol.removePalindromeSub("baabb")); // 2
    }
}
